# Generated by Django 4.2.11 on 2025-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=30)),
                ('Block', models.CharField(max_length=5)),
                ('Floar', models.IntegerField()),
                ('Rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('hq', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=20)),
                ('icon', models.FileField(null=True, upload_to='base/icon')),
                ('date_format', models.CharField(blank=True, max_length=30, null=True)),
                ('time_format', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'unique_together': {('company', 'address')},
            },
        ),
    ]
